# Generated by Django 4.2.5 on 2024-02-04 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_rename_usuario_proyecto_usuario_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proyecto',
            old_name='usuario_id',
            new_name='usuario',
        ),
    ]
